services:
  # User
  user:
    image: andhrib/fortune-rise-user
    build:
      context: ./user-microservice
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./user-microservice/.env
    volumes:
      - ./user-microservice/.env:/app/.env

  # Wallet
  wallet:
    image: andhrib/fortune-rise-wallet
    build:
      context: ./wallet-microservice
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - API_KEY=${API_KEY}
    env_file:
      - ./wallet-microservice/.env
    volumes:
      - ./wallet-microservice/.env:/app/.env

  # Game
  game:
    image: andhrib/fortune-rise-game
    build:
      context: ./game-microservice
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    env_file:
      - ./game-microservice/.env
    volumes:
      - ./game-microservice/.env:/app/.env

  # Notification
  notification:
    image: andhrib/fortune-rise-notification
    build:
      context: ./notification-microservice
    ports:
      - "8083:8083"
    depends_on:
      - postgres
    env_file:
      - ./notification-microservice/.env
    volumes:
      - ./notification-microservice/.env:/app/.env

  # Promotion
  promotion:
    image: andhrib/fortune-rise-promotion
    build:
      context: ./promotion-microservice
    ports:
      - "8084:8084"
    depends_on:
      - postgres
    env_file:
      - ./promotion-microservice/.env
    volumes:
      - ./promotion-microservice/.env:/app/.env

  # History
  history:
    image: andhrib/fortune-rise-history
    build:
      context: ./history-microservice
    ports:
      - "8085:8085"
    depends_on:
      - postgres
    env_file:
      - ./history-microservice/.env
    volumes:
      - ./history-microservice/.env:/app/.env

  # Database
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fortunerise
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
