apiVersion: v1
kind: Service
metadata:
  name: wallet
  labels:
    app: wallet
spec:
  type: ClusterIP # Internal access only
  selector:
    app: wallet # Must match pod labels
  ports:
    - port: 80 # Port exposed by the Service
      targetPort: 8081 # Container port to route to
      protocol: TCP
