kumuluzee:
  server:
    http:
      port: 8082
  name: fortune-rise
  version: 1.0.0
  env:
    name: dev
  datasources:
   - jndi-name : jdbc/FortuneRiseDS
     connection-url: jdbc:postgresql://localhost:5432/fortunerise
     username: postgres
     password: postgres
     max-pool-size: 20