apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend # Must match pod labels
  ports:
    - port: 80 # Port exposed by the Service
      targetPort: 4200 # Container port to route to
      protocol: TCP
