apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
  labels:
    app: game
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: game # Must match pod labels
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: andhrib/fortune-rise-game
          env:
            - name: DATABASE_HOSTNAME
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_NAME
              value: "postgres"
            - name: WALLET_HOST
              value: "wallet"
            - name: WALLET_PORT
              value: "80"
            - name: HISTORY_HOST
              value: "history"
            - name: HISTORY_PORT
              value: "80"
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 100m # Minimum CPU required
            limits:
              cpu: 500m # Maximum CPU the container can use