apiVersion: v1
kind: Service
metadata:
  name: history
  labels:
    app: history
spec:
  type: ClusterIP # Internal access only
  selector:
    app: history # Must match pod labels
  ports:
    - port: 80 # Port exposed by the Service
      targetPort: 8085 # Container port to route to
      protocol: TCP
