apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: notification # Must match pod labels
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: andhrib/fortune-rise-notification # Replace with your ACR image and tag
          env:
            - name: DATABASE_HOSTNAME
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_NAME
              value: "postgres"
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: 100m # Minimum CPU required
            limits:
              cpu: 500m # Maximum CPU the container can use