apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  type: ClusterIP # Internal access only
  selector:
    app: notification # Must match pod labels
  ports:
    - port: 80 # Port exposed by the Service
      targetPort: 8083 # Container port to route to
      protocol: TCP
