apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion
  labels:
    app: promotion
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: promotion # Must match pod labels
  template:
    metadata:
      labels:
        app: promotion
    spec:
      containers:
        - name: promotion
          image: andhrib/fortune-rise-promotion
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOSTNAME
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_NAME
              value: "postgres"
            - name: WALLET_HOST
              value: "wallet"
            - name: WALLET_PORT
              value: "80"
            - name: NOTIFICATION_HOST
              value: "notification"
            - name: NOTIFICATION_PORT
              value: "80"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8084
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8084
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 15
          ports:
            - containerPort: 8084
          resources:
            requests:
              cpu: 100m # Minimum CPU required
            limits:
              cpu: 200m # Maximum CPU the container can use