apiVersion: v1
kind: Service
metadata:
  name: promotion
  labels:
    app: promotion
spec:
  type: ClusterIP # Internal access only
  selector:
    app: promotion # Must match pod labels
  ports:
    - port: 80 # Port exposed by the Service
      targetPort: 8084 # Container port to route to
      protocol: TCP
