apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
  labels:
    app: wallet
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: wallet # Must match pod labels
  template:
    metadata:
      labels:
        app: wallet
    spec:
      containers:
        - name: wallet
          image: andhrib/fortune-rise-wallet
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOSTNAME
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "postgres"
            - name: DATABASE_NAME
              value: "postgres"
            - name: HISTORY_HOST
              value: "history"
            - name: HISTORY_PORT
              value: "80"
            - name: API_KEY
              valueFrom:
                configMapKeyRef:
                  name: wallet-config
                  key: API_KEY
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m # Minimum CPU required
            limits:
              cpu: 200m # Maximum CPU the container can use