name: CI/CD for Microservices

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  # Or use push or schedule if needed:
  # push:
  #   branches:
  #     - main
  # schedule:
  #   - cron: '0 0 * * *'  # Optional: Run every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Maven (Java) environment
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build each microservice with Maven
      - name: Build user
        run: |
          cd user-microservice
          mvn clean package

      - name: Build wallet
        run: |
          cd wallet-microservice
          mvn clean package

      - name: Build game
        run: |
          cd game-microservice
          mvn clean package

      - name: Build notification
        run: |
          cd notification-microservice
          mvn clean package

      - name: Build promotion
        run: |
          cd promotion-microservice
          mvn clean package

      - name: Build history
        run: |
          cd history-microservice
          mvn clean package


      # 4. Execute the docker compose
      - name: Execute docker compose
        run: |
          docker-compose build


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 5. Login to Docker Hub
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: andhrib
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Add these secrets in GitHub
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 6. Push Docker images to Docker hub
      - name: Push Docker images
        run: |
          docker-compose push

